apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flight-booking-app
  name: flight-booking-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-booking-app
  template:
    metadata:
      labels:
        app: flight-booking-app
    spec:
      imagePullSecrets:
        - name:  all-icr-io
      containers:
      - name: flight-booking-app
        image: de.icr.io/ek-test/flight-booking:v1
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flight-booking-app
  name: flight-booking-app-svc
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: flight-booking-app
  type: LoadBalancer
status:
  loadBalancer: {}

