apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: repository
      description: The git repo
    - name: revision
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: deploymentFile
      description: location and name of deployment file
    - name: registryNamespace
      description: the ibmcloud registry namespace
    - name: registryRegion
      description: the ibmcloud registry region
      default: eu-de
    - name: cluster
      description: The IBM Cloud Kubernetes cluster name
    - name: clusterRegion
      description: The IBM Cloud Kubernetes cluster region
      default: eu-de
    - name: clusterNamespace
      description: The Kubernetes cluster namespace
      default: default
    - name: imageName
      description: Name of the image
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: apikey
          value: $(params.apikey)
        - name: registryNamespace
          value: $(params.registryNamespace)
        - name: registryRegion
          value: $(params.registryRegion)
        - name: cluster
          value: $(params.cluster)
        - name: clusterRegion
          value: $(params.clusterRegion)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
        - name: deploymentFile
          value: $(params.deploymentFile)
        - name: imageName
          value: $(params.imageName)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: revision
      value: $(params.revision)
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
